# Week 1 Assignment: Basic Data Exploration and Cleaning using Pandas

### 1. Loading Dataset
 We'll be loading the 'combined_dataset.csv' (from Kaggle) into a Pandas DataFrame to begin our analysis.

In [2]:
#importing Pandas;
import pandas as pd
#Loading the dataset;
df = pd.read_csv('Combined_dataset.csv')

print("Dataset loaded successfully!")
#verifying the dataset;
print(df.head())

Dataset loaded successfully!
   product_id           title                         product_description  \
0     8376765     Lino Perros              Women Navy Blue Solid Backpack
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe

   rating  ratings_count  initial_price  discount  final_price currency  \
0     3.8             15           3995      58.0  "₹3,995.00"      INR
1     4.5             67           2899      35.0  "₹2,899.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
4     4.7             12           2899      17.0  "₹2,899.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/837...  ...
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
4  http://assets.myntassets.com/assets/images/pro...  ...

                                     amount_of_stars what_customers_said  \
0  {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN

  seller_name                                              sizes  \
0         NaN                               [{"size":"Onesize"}]
1         NaN                               [{"size":"Onesize"}]
2         NaN                                     [{"size":"S"}]
3         NaN                               [{"size":"Onesize"}]
4         NaN  [{"size":"M","value":"45.0in","value_name":"Fr...

                                              videos seller_information  \
0                              ["rw-8376765_cae700"]                NaN
1                              ["rw-9136281_cae700"]                NaN
2  ["https://videos.myntassets.com/assets/videos/...                NaN
3  ["https://videos.myntassets.com/assets/videos/...                NaN
4                                                NaN                NaN

                                    variations best_offer  \
0                                         [{}]         {}
1                                      [{},{}]         {}
2                          [{},{},{},{},{},{}]         {}
3                                          NaN         {}
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]         {}

                                         more_offers   category
0  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4  [{"offer_name":"10% Instant Discount on IndusI...  bath-robe

[5 rows x 24 columns]

### 2. Exploring the Data
Checking the shape, column names and data types

In [5]:
#getting dataset structure;
print("Dataset Structure (Shape) :", df.shape)
#getting the first 5 rows;
print("\nFirst 5 rows of the dataset :")
print(df.head())
#getting the last 5 rows;
print("\nLast 5 rows of the dataset :")
print(df.tail())
#getting the column information;
print("\nColumn information :")
print(df.info())
#getting data types explicitly as well(however) it is also shown in the info() method;
print("\nData types of each column :")
print(df.dtypes)
#getting summary statistics of the dataset;
df.describe()

Dataset Structure (Shape) : (1000, 24)

First 5 rows of the dataset :
   product_id           title                         product_description  \
0     8376765     Lino Perros              Women Navy Blue Solid Backpack
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe

   rating  ratings_count  initial_price  discount  final_price currency  \
0     3.8             15           3995      58.0  "₹3,995.00"      INR
1     4.5             67           2899      35.0  "₹2,899.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
4     4.7             12           2899      17.0  "₹2,899.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/837...  ...
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
4  http://assets.myntassets.com/assets/images/pro...  ...

                                     amount_of_stars what_customers_said  \
0  {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN

  seller_name                                              sizes  \
0         NaN                               [{"size":"Onesize"}]
1         NaN                               [{"size":"Onesize"}]
2         NaN                                     [{"size":"S"}]
3         NaN                               [{"size":"Onesize"}]
4         NaN  [{"size":"M","value":"45.0in","value_name":"Fr...

                                              videos seller_information  \
0                              ["rw-8376765_cae700"]                NaN
1                              ["rw-9136281_cae700"]                NaN
2  ["https://videos.myntassets.com/assets/videos/...                NaN
3  ["https://videos.myntassets.com/assets/videos/...                NaN
4                                                NaN                NaN

                                    variations best_offer  \
0                                         [{}]         {}
1                                      [{},{}]         {}
2                          [{},{},{},{},{},{}]         {}
3                                          NaN         {}
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]         {}

                                         more_offers   category
0  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4  [{"offer_name":"10% Instant Discount on IndusI...  bath-robe

[5 rows x 24 columns]

Last 5 rows of the dataset :
     product_id     title                                product_description  \
995    13698258     KREDO  Men FORTE Silver Automatic Skeleton Analogue W...
996    16896006     GUESS  Women White Patterned Dial & White Straps Anal...
997     1708108  GIORDANO  Women Rose Gold-Toned Mirrored Analogue Watch ...
998    19280114  Fastrack  Men Black Brass Dial & Black Stainless Steel S...
999    18601682   BOLDFIT                           Purple Textured Yoga Mat

     rating  ratings_count  initial_price  discount   final_price currency  \
995     3.5             11          11890      50.0  "₹11,890.00"      INR
996     5.0             22           8900      45.0   "₹8,900.00"      INR
997     2.8              5           7950      50.0   "₹7,950.00"      INR
998     4.3             17           3295      20.0   "₹2,636.00"      INR
999     3.8            161            699      31.0     "₹699.00"      INR

                                                images  ...  \
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                 sizes  \
995             NaN  [{"size":"Onesize"}]
996             NaN  [{"size":"Onesize"}]
997             NaN  [{"size":"Onesize"}]
998  Tru███m R███il  [{"size":"Onesize"}]
999             NaN   [{"size":"Medium"}]

                                                videos  \
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                    variations  \
995                        NaN
996                        NaN
997  [{},{},{},{},{},{},{},{}]
998                        NaN
999              [{},{},{},{}]

                                            best_offer  \
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[5 rows x 24 columns]

Column information :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB
None

Data types of each column :
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

### 3. Handling Missing Values
We'll first identify which columns contain null (NaN) values. And, then based on the count we'll decide whether to fill them with statistical averages or drop the rows to maintain the data quality.

In [9]:
print("Initial Missing values:")
print(df.isnull().sum())

Initial Missing values:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [ ]:
#filling disciptive columns with a 'Not Available' value;
descriptive_columns = ['what_customers_said','seller_name','videos', 'seller_information','variations']
df[descriptive_columns] = df[descriptive_columns].fillna('Not Available')


#filling discount column with 0 as it is a numerical column and need to be filled with a numerical value;
df['discount'] = df['discount'].fillna(0)

# dropping remaining rows that might have critical missing values in other columns;
df.dropna(inplace=True)

#verifying the results after handling missing values;
print("Final Missing values count after handling :", df.isnull().sum().sum())

Final Missing values count after handling : 0

### 4. Performing Basic Operations (Filter & Select)
Demonstrating row filtering based on ratings and selecting a subset of relevant columns.

In [14]:
# Selecting specific columns
selected_columns = df[['title', 'rating', 'final_price']]
print(selected_columns.head())

# Filter rows: Show only products with a rating higher than 4.0
high_rated_products = df[df['rating'] > 4.0]

print(f"Number of high-rated products: {len(high_rated_products)}")
high_rated_products.head()

            title  rating  final_price
0     Lino Perros     3.8  "₹3,995.00"
1  Tommy Hilfiger     4.5  "₹2,899.00"
2           Lavie     4.4  "₹2,999.00"
3          F Gear     4.4  "₹1,675.00"
4       MYTRIDENT     4.7  "₹2,899.00"
Number of high-rated products: 533

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Not Available,Not Available,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Not Available,Not Available,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",Not Available,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Not Available,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

### 5. Removing Duplicates
We'll ensure that each product entry is unique

In [18]:
# we will check the shape before removing duplicates to see how many duplicates were removed
print(f"Shape before removing duplicates: {df.shape}")
initial_rows = df.shape[0]
# now removing duplicate rows 
df.drop_duplicates(inplace=True)

final_rows = df.shape[0]

print(f"Shape after removing duplicates: {df.shape}")
print(f"Number of duplicate rows removed: {initial_rows - final_rows}")

Shape before removing duplicates: (1000, 24)
Shape after removing duplicates: (1000, 24)
Number of duplicate rows removed: 0

### 6. Creating a Derived Column 'total_amount'
Before calculating the total amount, we must clean the price columns by removing currency symbols and commas, then convert them to numeric types. We will then calculate 'total_amount' as 'final_price' * 'quantity'.

In [35]:

# We remove double quotes, currency symbol, and commas
df['final_price_cleaned'] = df['final_price'].str.replace('"', '', regex=False)
df['final_price_cleaned'] = df['final_price_cleaned'].str.replace('₹', '', regex=False)
df['final_price_cleaned'] = df['final_price_cleaned'].str.replace(',', '', regex=False)
df['final_price_cleaned'] = df['final_price_cleaned'].str.strip()

# Convert to numeric value, coercing errors to NaN (in case there are any non-numeric values left)
df['final_price_cleaned'] = pd.to_numeric(df['final_price_cleaned'], errors='coerce')

# Handle any remaining NaNs (just in case)
df['final_price_cleaned'] = df['final_price_cleaned'].fillna(0)

# let us now make a column 'quantity' and fill it with 1 as we are considering this quantity for each product;
df['quantity'] = 1

#now creating a derived 'total_amount'
df['total_amount'] = df['final_price_cleaned'] * df['quantity']

#verifying if our math works correctly by showing the relevant columns;
df[['title', 'final_price', 'final_price_cleaned', 'quantity', 'total_amount']].head()

            title  final_price  final_price_cleaned  quantity  total_amount
0     Lino Perros  "₹3,995.00"               3995.0         1        3995.0
1  Tommy Hilfiger  "₹2,899.00"               2899.0         1        2899.0
2           Lavie  "₹2,999.00"               2999.0         1        2999.0
3          F Gear  "₹1,675.00"               1675.0         1        1675.0
4       MYTRIDENT  "₹2,899.00"               2899.0         1        2899.0